# Generated by Django 3.1.1 on 2021-09-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(max_length=8),
        ),
    ]
