# Generated by Django 3.1.1 on 2021-10-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210928_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adress', to='users.adress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress_billing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adress_billing', to='users.adress'),
        ),
    ]
