# Generated by Django 3.1.1 on 2021-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211025_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('0', 'Cancelada'), ('1', 'A Aguardar Pagamento'), ('2', 'Pagamento Confirmado'), ('3', 'Em Processamento'), ('4', 'Enviado')], max_length=1),
        ),
    ]
