# Generated by Django 3.1.1 on 2021-06-09 12:47

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210607_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default.png', upload_to=products.models.product_directory_path),
        ),
    ]
