# Generated by Django 3.1.1 on 2021-06-09 12:48

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210609_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to=products.models.product_directory_path),
        ),
    ]
